<?php
include_once(drupal_get_path('module', 'oc_sidr_menu').'/oc_sidr_menu.admin.php');
/*
 * Menu
 */
function oc_sidr_menu_menu()
{
     $items['admin/ocsidrmenu/config'] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('oc_sidr_menu_admin'),
      'type' => MENU_CALLBACK,
      'access arguments' => array('access content'),
    );
    return $items;
}
/*
 * Register block
 */
function oc_sidr_menu_block_info() {
  // This example comes from node.module.
  $blocks['sidr_menu'] = array(
    'info' => t('Sidr Menu'),
    // DRUPAL_CACHE_PER_ROLE will be assumed.
  );

  return $blocks;
}
/*
 * Handle Block View
 */
function oc_sidr_menu_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
     case 'sidr_menu':
      if (user_access('access content')) {
            drupal_add_js(drupal_get_path('module', 'oc_sidr_menu') . '/js/oc_sidr_menu.js');
            drupal_add_js(drupal_get_path('module', 'oc_sidr_menu') . '/js/jquery.sidr.min.js');
            drupal_add_js(drupal_get_path('module', 'oc_sidr_menu') . '/js/jquery.touchSwipe.min.js');
            drupal_add_css(drupal_get_path('module', 'oc_sidr_menu') . '/css/oc_sidr_menu.css');
            drupal_add_css(drupal_get_path('module', 'oc_sidr_menu') . '/css/jquery.sidr.dark.css');
            drupal_add_js(array('oc_sidr_menu' => array('btn_selector' => variable_get('oc_sidr_menu_selector',''))), 'setting');
            
            $block['content'] = theme('oc_sidr_menu',array('menus' => array(variable_get('oc_sidr_selected_menu','')),'footer_html' => variable_get('oc_sidr_menu_footer_html','')
                , 'header_html' => variable_get('oc_sidr_menu_header_html','')));
        }
        else {
          $block['content'] = '';
        }
      break;
  }
  return $block;
}
 /*
  * Register a custom theme template
  */
 function oc_sidr_menu_theme($existing, $type, $theme, $path)
{
    return array(
      'oc_sidr_menu' => array(
        'variables' => array('menu'=>NULL,'footer_html' => NULL),
        'template' => 'oc_sidr_menu',
        'path' => drupal_get_path('module', 'oc_sidr_menu') . '/templates'
      ),
    );
}